# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    vb.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', '2',
        '--type', 'dvddrive', '--medium', 'user-data.iso']
    vb.gui = false
    vb.cpus = 2
    vb.memory = "4096"
  end

  command = "cat /var/log/cloud-init-output.log"
  config.vm.provision :shell, :inline => command
end
